CREATE DATABASE IF NOT EXISTS ENTERPRISE_MOBILITY;
CREATE SCHEMA IF NOT EXISTS ENTERPRISE_MOBILITY.TLC;
USE DATABASE ENTERPRISE_MOBILITY;
USE SCHEMA TLC;
SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();

CREATE OR REPLACE TABLE ENTERPRISE_MOBILITY.TLC.MONTHLY_MOBILITY (
    MONTH_YEAR DATE,
    LICENSE_CLASS VARCHAR,
    TRIPS_PER_DAY NUMBER,
    FAREBOX_PER_DAY NUMBER,
    UNIQUE_DRIVERS NUMBER,
    UNIQUE_VEHICLES NUMBER,
    VEHICLES_PER_DAY NUMBER,
    AVG_DAYS_VEHICLES_ON_ROAD FLOAT,
    AVG_HOURS_PER_DAY_PER_VEHICLE FLOAT,
    AVG_DAYS_DRIVERS_ON_ROAD FLOAT,
    AVG_HOURS_PER_DAY_PER_DRIVER FLOAT,
    AVG_MINUTES_PER_TRIP FLOAT,
    PERCENT_OF_TRIPS_PAID_WITH_CREDIT_CARD FLOAT,
    TRIPS_PER_DAY_SHARED NUMBER
);
SELECT COUNT(*) AS ROW_COUNT
FROM ENTERPRISE_MOBILITY.TLC.MONTHLY_MOBILITY;
SELECT *
FROM ENTERPRISE_MOBILITY.TLC.MONTHLY_MOBILITY
LIMIT 10;

-- Check total rows
SELECT COUNT(*) AS TOTAL_ROWS
FROM ENTERPRISE_MOBILITY.TLC.MONTHLY_MOBILITY;

-- Check missing values
SELECT
    COUNT_IF(MONTH_YEAR IS NULL) AS NULL_MONTH_YEAR,
    COUNT_IF(LICENSE_CLASS IS NULL) AS NULL_LICENSE_CLASS,
    COUNT_IF(TRIPS_PER_DAY IS NULL) AS NULL_TRIPS_PER_DAY,
    COUNT_IF(FAREBOX_PER_DAY IS NULL) AS NULL_FAREBOX_PER_DAY,
    COUNT_IF(UNIQUE_DRIVERS IS NULL) AS NULL_UNIQUE_DRIVERS,
    COUNT_IF(UNIQUE_VEHICLES IS NULL) AS NULL_UNIQUE_VEHICLES
FROM ENTERPRISE_MOBILITY.TLC.MONTHLY_MOBILITY;

-- Check license categories
SELECT
    LICENSE_CLASS,
    COUNT(*) AS RECORD_COUNT
FROM ENTERPRISE_MOBILITY.TLC.MONTHLY_MOBILITY
GROUP BY LICENSE_CLASS
ORDER BY RECORD_COUNT DESC;

-- Basic business metrics
SELECT
    MIN(MONTH_YEAR) AS FIRST_MONTH,
    MAX(MONTH_YEAR) AS LAST_MONTH,
    SUM(TRIPS_PER_DAY) AS TOTAL_TRIPS_PER_DAY,
    AVG(TRIPS_PER_DAY) AS AVG_TRIPS_PER_DAY,
    AVG(UNIQUE_DRIVERS) AS AVG_UNIQUE_DRIVERS,
    AVG(UNIQUE_VEHICLES) AS AVG_UNIQUE_VEHICLES
FROM ENTERPRISE_MOBILITY.TLC.MONTHLY_MOBILITY;

-- Check total rows
SELECT COUNT(*) AS TOTAL_ROWS
FROM ENTERPRISE_MOBILITY.TLC.MONTHLY_MOBILITY;

-- Check missing values
SELECT
    COUNT_IF(MONTH_YEAR IS NULL) AS NULL_MONTH_YEAR,
    COUNT_IF(LICENSE_CLASS IS NULL) AS NULL_LICENSE_CLASS,
    COUNT_IF(TRIPS_PER_DAY IS NULL) AS NULL_TRIPS_PER_DAY,
    COUNT_IF(FAREBOX_PER_DAY IS NULL) AS NULL_FAREBOX_PER_DAY,
    COUNT_IF(UNIQUE_DRIVERS IS NULL) AS NULL_UNIQUE_DRIVERS,
    COUNT_IF(UNIQUE_VEHICLES IS NULL) AS NULL_UNIQUE_VEHICLES
FROM ENTERPRISE_MOBILITY.TLC.MONTHLY_MOBILITY;

-- Check license categories
SELECT
    LICENSE_CLASS,
    COUNT(*) AS RECORD_COUNT
FROM ENTERPRISE_MOBILITY.TLC.MONTHLY_MOBILITY
GROUP BY LICENSE_CLASS
ORDER BY RECORD_COUNT DESC;

CREATE OR REPLACE VIEW ENTERPRISE_MOBILITY.TLC.VW_MONTHLY_MOBILITY AS
SELECT
    MONTH_YEAR,
    LICENSE_CLASS,
    TRIPS_PER_DAY,
    FAREBOX_PER_DAY,
    UNIQUE_DRIVERS,
    UNIQUE_VEHICLES,
    VEHICLES_PER_DAY,
    AVG_DAYS_VEHICLES_ON_ROAD,
    AVG_HOURS_PER_DAY_PER_VEHICLE,
    AVG_DAYS_DRIVERS_ON_ROAD,
    AVG_HOURS_PER_DAY_PER_DRIVER,
    AVG_MINUTES_PER_TRIP,
    PERCENT_OF_TRIPS_PAID_WITH_CREDIT_CARD,
    TRIPS_PER_DAY_SHARED
FROM ENTERPRISE_MOBILITY.TLC.MONTHLY_MOBILITY;

SELECT *
FROM ENTERPRISE_MOBILITY.TLC.VW_MONTHLY_MOBILITY
LIMIT 10;

-- ==========================================
-- ENTERPRISE MOBILITY KPI ANALYSIS
-- ==========================================

-- 1. Overall KPIs
SELECT
    SUM(TRIPS_PER_DAY) AS TOTAL_TRIPS,
    AVG(TRIPS_PER_DAY) AS AVG_TRIPS_PER_DAY,
    AVG(UNIQUE_DRIVERS) AS AVG_UNIQUE_DRIVERS,
    AVG(UNIQUE_VEHICLES) AS AVG_UNIQUE_VEHICLES,
    AVG(FAREBOX_PER_DAY) AS AVG_FAREBOX_PER_DAY
FROM ENTERPRISE_MOBILITY.TLC.VW_MONTHLY_MOBILITY;


-- 2. Trips by license class
SELECT
    LICENSE_CLASS,
    SUM(TRIPS_PER_DAY) AS TOTAL_TRIPS,
    AVG(TRIPS_PER_DAY) AS AVG_TRIPS_PER_DAY,
    AVG(UNIQUE_DRIVERS) AS AVG_UNIQUE_DRIVERS
FROM ENTERPRISE_MOBILITY.TLC.VW_MONTHLY_MOBILITY
GROUP BY LICENSE_CLASS
ORDER BY TOTAL_TRIPS DESC;


-- 3. Monthly trip trend
SELECT
    MONTH_YEAR,
    SUM(TRIPS_PER_DAY) AS TOTAL_TRIPS
FROM ENTERPRISE_MOBILITY.TLC.VW_MONTHLY_MOBILITY
GROUP BY MONTH_YEAR
ORDER BY MONTH_YEAR;


-- 4. Drivers vs vehicles
SELECT
    MONTH_YEAR,
    SUM(UNIQUE_DRIVERS) AS TOTAL_DRIVERS,
    SUM(UNIQUE_VEHICLES) AS TOTAL_VEHICLES
FROM ENTERPRISE_MOBILITY.TLC.VW_MONTHLY_MOBILITY
GROUP BY MONTH_YEAR
ORDER BY MONTH_YEAR;

CREATE OR REPLACE VIEW ENTERPRISE_MOBILITY.TLC.VW_MOBILITY_KPIS AS
SELECT
    MONTH_YEAR,
    LICENSE_CLASS,

    TRIPS_PER_DAY,
    FAREBOX_PER_DAY,

    UNIQUE_DRIVERS,
    UNIQUE_VEHICLES,

    VEHICLES_PER_DAY,

    AVG_DAYS_VEHICLES_ON_ROAD,
    AVG_HOURS_PER_DAY_PER_VEHICLE,

    AVG_DAYS_DRIVERS_ON_ROAD,
    AVG_HOURS_PER_DAY_PER_DRIVER,

    AVG_MINUTES_PER_TRIP,

    PERCENT_OF_TRIPS_PAID_WITH_CREDIT_CARD,

    TRIPS_PER_DAY_SHARED,

    -- Derived KPI
    CASE
        WHEN UNIQUE_VEHICLES > 0
        THEN TRIPS_PER_DAY / UNIQUE_VEHICLES
        ELSE NULL
    END AS TRIPS_PER_VEHICLE,

    CASE
        WHEN UNIQUE_DRIVERS > 0
        THEN TRIPS_PER_DAY / UNIQUE_DRIVERS
        ELSE NULL
    END AS TRIPS_PER_DRIVER

FROM ENTERPRISE_MOBILITY.TLC.MONTHLY_MOBILITY;

SELECT *
FROM ENTERPRISE_MOBILITY.TLC.VW_MOBILITY_KPIS
LIMIT 10;

CREATE OR REPLACE VIEW ENTERPRISE_MOBILITY.TLC.VW_POWERBI_MONTHLY AS
SELECT
    MONTH_YEAR,

    SUM(TRIPS_PER_DAY) AS TOTAL_TRIPS,
    SUM(UNIQUE_DRIVERS) AS TOTAL_DRIVERS,
    SUM(UNIQUE_VEHICLES) AS TOTAL_VEHICLES,

    SUM(FAREBOX_PER_DAY) AS TOTAL_FAREBOX,

    AVG(TRIPS_PER_DAY) AS AVG_TRIPS_PER_DAY,
    AVG(FAREBOX_PER_DAY) AS AVG_FAREBOX_PER_DAY,

    AVG(PERCENT_OF_TRIPS_PAID_WITH_CREDIT_CARD)
        AS AVG_CREDIT_CARD_PERCENT,

    AVG(TRIPS_PER_DAY_SHARED)
        AS AVG_SHARED_TRIPS,

    SUM(TRIPS_PER_DAY) / NULLIF(SUM(UNIQUE_VEHICLES), 0)
        AS TRIPS_PER_VEHICLE,

    SUM(TRIPS_PER_DAY) / NULLIF(SUM(UNIQUE_DRIVERS), 0)
        AS TRIPS_PER_DRIVER

FROM ENTERPRISE_MOBILITY.TLC.MONTHLY_MOBILITY

GROUP BY MONTH_YEAR
ORDER BY MONTH_YEAR;

SELECT *
FROM ENTERPRISE_MOBILITY.TLC.VW_POWERBI_MONTHLY
ORDER BY MONTH_YEAR;

SELECT *
FROM ENTERPRISE_MOBILITY.TLC.VW_POWERBI_MONTHLY
ORDER BY MONTH_YEAR;

SELECT
    CURRENT_ACCOUNT() AS ACCOUNT_IDENTIFIER,
    CURRENT_REGION() AS REGION;